### ISSUE TITLE
Unable to find texture error if file extension characters are in uppercase 

### ISSUE THREAD

**Issue by brnrdbrk** [fLindahl/map-to-gltf#5]
Got some textures that had UPPERCASE file extensions and mtg was unable to find textures and spitted out a error.

Bug is probably related to line 269 in map.cpp:

`
const char* supportedExts[3] = { ".png", ".jpg", ".bmp" };
`

**Comment by fLindahl** [comment]
I think f2787ae should fix it!

Thanks :)

**Comment by brnrdbrk** [comment]
Simple fix! :D
I was not confident enough proposing that with a PR and thought you would prefer a fancier solution. Thanks!
