### ISSUE TITLE
Can't get mtg/trenchbroom to compile

### ISSUE THREAD

**Issue by carnifexx** [fLindahl/map-to-gltf#6]
sorry for bothering you guys with this.
not sure what I do wrong, but trenchbroom won't compile a gltf file.
i did exactly what is stated in the documentation (at least i think i did).
would it be possible to create a better documentation?

**Comment by fLindahl** [comment]
Does it give you any errors? What are you passing as arguments to the cli?

**Comment by carnifexx** [comment]
i guess i didn't really get that it is only a cli tool
![yM5ebd1 1](https://github.com/fLindahl/map-to-gltf/assets/844546/6b6881d7-4120-43de-89b0-107caa769ae7)
